# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{haml_rails}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rafael Felix"]
  s.date = %q{2010-11-07}
  s.description = %q{HAML scaffold template engine}
  s.email = %q{felix.rafael@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    "init.rb",
     "lib/generators/haml_rails/install_generator.rb",
     "lib/generators/haml_rails/templates/controller/controller_generator.rb",
     "lib/generators/haml_rails/templates/controller/templates/view.html.haml",
     "lib/generators/haml_rails/templates/mailer/mailer_generator.rb",
     "lib/generators/haml_rails/templates/mailer/templates/view.text.haml",
     "lib/generators/haml_rails/templates/scaffold/scaffold_generator.rb",
     "lib/generators/haml_rails/templates/scaffold/templates/_form.html.haml",
     "lib/generators/haml_rails/templates/scaffold/templates/edit.html.haml",
     "lib/generators/haml_rails/templates/scaffold/templates/index.html.haml",
     "lib/generators/haml_rails/templates/scaffold/templates/layout.html.haml",
     "lib/generators/haml_rails/templates/scaffold/templates/new.html.haml",
     "lib/generators/haml_rails/templates/scaffold/templates/show.html.haml",
     "lib/haml_rails.rb",
     "lib/version.rb"
  ]
  s.homepage = %q{http://github.com/fellix/haml_rails}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{HAML scaffold template engine}
  s.test_files = [
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

